### ISSUE TITLE
Exception Error During Booting

### ISSUE THREAD

**Issue by OptimusPlays** [jolbol1/RandomCoordinatesV2#24]
- [ ] 1.11+
- [ ] 1.10+
- [ ] 1.9+
- [ x] 1.8 +
- [ ] 1.7+

## Issue Description
During boot up this message pops up and whenever i use rc command this shows.

## Additional Information
11:06:09 [SEVERE] Could not pass event PlayerTeleportEvent to RandomCoords v0.5.8-RELEASE
11:06:09 org.bukkit.event.EventException
11:06:10 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
11:06:10 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
11:06:10 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
11:06:10 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
11:06:10 	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.teleport(CraftPlayer.java:444) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
11:06:10 	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftEntity.teleport(CraftEntity.java:226) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
11:06:11 	at com.jolbol1.RandomCoordinates.managers.CoordinatesManager.lambda$scheduleTeleport$0(CoordinatesManager.java:440) ~[?:?]
11:06:11 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
11:06:11 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
11:06:11 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
11:06:11 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
11:06:11 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
11:06:11 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
11:06:11 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
11:06:11 Caused by: java.lang.NoSuchFieldError: END_GATEWAY
11:06:12 	at com.jolbol1.RandomCoordinates.listeners.PlayerSwitchWorld.onPlayerSwitch(PlayerSwitchWorld.java:44) ~[?:?]
11:06:12 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
11:06:12 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
11:06:12 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
11:06:12 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
11:06:12 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
11:06:12 	... 13 more

**Comment by jolbol1** [comment]
Sorry for how late this is but this seems to be a 1.8 compatibility issue, It's looking for End Gateways, Something non-existent in 1.8. Closing as I am looking into a fix.
