### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ghost** [jolbol1/RandomCoordinatesV2#27]
timings
https://timings.aikar.co/?id=65051074f4a748029c5de12cdd01f6ce

logs
```
[04:07:50] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to RandomCoords v0.6.2-RELEASE
java.lang.NoClassDefFoundError: br/net/fabiozumbi12/RedProtect/API/RedProtectAPI
	at com.jolbol1.RandomCoordinates.checks.RedProtect.redProtectClaimNearby(RedProtect.java:111) ~[?:?]
	at com.jolbol1.RandomCoordinates.managers.CoordinatesManager.isTheLocationSafe(CoordinatesManager.java:228) ~[?:?]
	at com.jolbol1.RandomCoordinates.managers.CoordinatesManager.getSafeRandomLocation(CoordinatesManager.java:296) ~[?:?]
	at com.jolbol1.RandomCoordinates.managers.CoordinatesManager.randomlyTeleportPlayer(CoordinatesManager.java:360) ~[?:?]
	at com.jolbol1.RandomCoordinates.listeners.SignClick.onClickEvent(SignClick.java:71) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor354.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1222]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1222]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1222]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514) ~[patched_1.12.2.jar:git-Paper-1222]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) ~[patched_1.12.2.jar:git-Paper-1222]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:235) ~[patched_1.12.2.jar:git-Paper-1222]
	at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:458) ~[patched_1.12.2.jar:git-Paper-1222]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:955) ~[patched_1.12.2.jar:git-Paper-1222]
	at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[patched_1.12.2.jar:git-Paper-1222]
	at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.12.2.jar:git-Paper-1222]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1222]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [patched_1.12.2.jar:git-Paper-1222]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [patched_1.12.2.jar:git-Paper-1222]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [patched_1.12.2.jar:git-Paper-1222]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1222]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1222]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
[04:07:50] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to RandomCoords v0.6.2-RELEASE
java.lang.NoClassDefFoundError: br/net/fabiozumbi12/RedProtect/API/RedProtectAPI
	at com.jolbol1.RandomCoordinates.checks.RedProtect.redProtectClaimNearby(RedProtect.java:111) ~[?:?]
	at com.jolbol1.RandomCoordinates.managers.CoordinatesManager.isTheLocationSafe(CoordinatesManager.java:228) ~[?:?]
	at com.jolbol1.RandomCoordinates.managers.CoordinatesManager.getSafeRandomLocation(CoordinatesManager.java:296) ~[?:?]
	at com.jolbol1.RandomCoordinates.managers.CoordinatesManager.randomlyTeleportPlayer(CoordinatesManager.java:360) ~[?:?]
	at com.jolbol1.RandomCoordinates.listeners.SignClick.onClickEvent(SignClick.java:71) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor354.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1222]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1222]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1222]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514) ~[patched_1.12.2.jar:git-Paper-1222]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) ~[patched_1.12.2.jar:git-Paper-1222]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:235) ~[patched_1.12.2.jar:git-Paper-1222]
	at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:458) ~[patched_1.12.2.jar:git-Paper-1222]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:955) ~[patched_1.12.2.jar:git-Paper-1222]
	at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[patched_1.12.2.jar:git-Paper-1222]
	at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.12.2.jar:git-Paper-1222]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1222]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [patched_1.12.2.jar:git-Paper-1222]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [patched_1.12.2.jar:git-Paper-1222]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [patched_1.12.2.jar:git-Paper-1222]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1222]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1222]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```

**Comment by FabioZumbi12** [comment]
> java.lang.NoClassDefFoundError: br/net/fabiozumbi12/RedProtect/API/RedProtectAPI

`NoClassDefFoundError` means the plugin is using redprotect as api hooked with an outdated version of redprotect, or redprotect is not loaded on server.
